import groovy.json.JsonSlurper;

node {
  stage('Select Branch')    
    a = getBranchList()
    choice_branch = new ChoiceParameterDefinition('Branch', a as String[], 'Select Branch Name')
    def branch_input = input message: 'Select Branch', parameters: [choice_branch]
    def branchName = branch_input.replace("'", "")

  stage('Select Artifact')
    b = getArtifactList(branchName)
    choice_artifacts = new ChoiceParameterDefinition('Artifact', b as String[], 'Select Artifact Name')
    def art_input = input message: 'Select Artifact', parameters: [choice_artifacts]
    println(art_input)
}

def getBranchList() {
  def API_URL = "https://raw.githubusercontent.com/vijayg92/jenkins-pipeline/master/artifacts/artifacts.json"
  def conn = API_URL.toURL().openConnection()
  def branch_list = []
 
  if( conn.responseCode == 200 ) {
      def results = new JsonSlurper().parseText(conn.content.text)
      def branch = results['children']['uri']
      branch.each { id -> 
                branch_list.push("'"+id+"'")
      }
  }
  return branch_list
}

def getArtifactList(branchName) {
  def branch = branchName
  def API_URL = "https://raw.githubusercontent.com/vijayg92/jenkins-pipeline/master/artifacts${branch}/artifacts-child.json"
  def conn = API_URL.toURL().openConnection()
  def artifact_list = []
 
  if( conn.responseCode == 200 ) {
      def results = new JsonSlurper().parseText(conn.content.text)
      def arts = results['children']['uri']
      println(arts)
      arts.each { id -> 
                arts.push("'"+id+"'")
      }
  }
  return artifact_list
}
